In [4]:
import numpy as np

In [3]:
print(np.__version__)

2.1.3


In [3]:
lst = [1,9,5,2]

In [4]:
print(lst)

[1, 9, 5, 2]


In [6]:
arr = np.array(lst)

In [7]:
print(arr)

[1 9 5 2]


In [14]:
my_matrix = [[1,2,3,4,5],[9,0,5,4,3]]

In [16]:
mat = np.array(my_matrix)

In [17]:
print(mat)

[[1 2 3 4 5]
 [9 0 5 4 3]]


In [36]:
np.arange(3.1)

array([0., 1., 2., 3.])

In [37]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [40]:
np.zeros(3)

array([0., 0., 0.])

In [41]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [55]:
np.zeros((3,2,4),dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [52]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [56]:
np.ones(3)

array([1., 1., 1.])

In [61]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [62]:
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [65]:
np.linspace(0,10,5,endpoint=True)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [66]:
np.linspace(0,10,5,endpoint=False)

array([0., 2., 4., 6., 8.])

In [67]:
np.linspace(0,10,5,endpoint=True,retstep=True)

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), np.float64(2.5))

In [68]:
np.linspace(0,10,5,endpoint=False,retstep=True)

(array([0., 2., 4., 6., 8.]), np.float64(2.0))

In [70]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [72]:
np.eye(5,4,k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
np.eye(5,4,k=2,dtype=int)

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [76]:
np.random.rand(2)

array([0.35887026, 0.67406566])

In [78]:
np.random.rand(4,5)

array([[0.87665812, 0.32891981, 0.46883569, 0.16124595, 0.77880122],
       [0.31370587, 0.79508518, 0.53051485, 0.61759986, 0.27856495],
       [0.24743461, 0.66449201, 0.31735993, 0.09210957, 0.7045902 ],
       [0.26329506, 0.46347694, 0.97812289, 0.00989908, 0.62577439]])

In [79]:
np.random.randn(3,4)

array([[-0.89279144,  0.80626553,  0.3668652 ,  0.9375771 ],
       [-0.82257953,  0.60352724, -0.88141102, -0.25522905],
       [ 0.08451248, -0.49864164,  1.16446086,  0.77447438]])

In [82]:
np.random.randint(6)

5

In [85]:
np.random.randint(6,10)

8

In [84]:
np.random.randint(6,10,size=5)

array([7, 6, 6, 8, 9], dtype=int32)

In [86]:
arr = np.arange(25)

In [88]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [5]:
ranarr = np.random.randint(0,25,25)

In [6]:
print(ranarr)

[ 8  5 20 24 21  8 17 11  5 19 20  7 23 23  4  6 15 14 23  2  9 21 23  0
 17]


In [7]:
arr.reshape(5,5)

NameError: name 'arr' is not defined

In [8]:
arr.reshape(2,3)

NameError: name 'arr' is not defined

In [9]:
arr.reshape(5,6)

NameError: name 'arr' is not defined

In [10]:
print(ranarr)

[ 8  5 20 24 21  8 17 11  5 19 20  7 23 23  4  6 15 14 23  2  9 21 23  0
 17]


In [11]:
print(ranarr.max())

24


In [12]:
print(ranarr.min())

0


In [13]:
print('index of max : {}'.format(ranarr.argmax()))

index of max : 3


In [6]:
print("min {}".format(ranarr.argmin()))

min 9


In [1]:
# check git hub yesterday work