# 1D array

In [37]:
import numpy as np

In [3]:
arr = np.arange(4,28,3)

In [4]:
print(arr)

[ 4  7 10 13 16 19 22 25]


In [5]:
arr[0:5]

array([ 4,  7, 10, 13, 16])

In [6]:
arr[3]

np.int64(13)

In [8]:
arr[3:]

array([13, 16, 19, 22, 25])

In [15]:
arr[7:8]

array([25])

In [16]:
arr[:5]=100

In [17]:
arr

array([100, 100, 100, 100, 100,  19,  22,  25])

In [18]:
arr = np.arange(0,11)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
slice_arr = arr[:5]

In [21]:
slice_arr

array([0, 1, 2, 3, 4])

In [22]:
slice_arr[:]=1000

In [23]:
slice_arr

array([1000, 1000, 1000, 1000, 1000])

In [24]:
arr

array([1000, 1000, 1000, 1000, 1000,    5,    6,    7,    8,    9,   10])

In [25]:
arr[1:3]=99

In [26]:
slice_arr

array([1000,   99,   99, 1000, 1000])

In [27]:
arr_1=np.arange(0,11)

In [28]:
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr_2=arr_1.copy()
arr_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
slice_arr2=arr_2[:8]

In [31]:
slice_arr2[:]=111

In [32]:
slice_arr2

array([111, 111, 111, 111, 111, 111, 111, 111])

In [33]:
arr_2

array([111, 111, 111, 111, 111, 111, 111, 111,   8,   9,  10])

In [34]:
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 2D array

In [46]:
arr_2d = np.array([[5,10,15],[25,30,35],[45,50,55]])

In [47]:
arr_2d

array([[ 5, 10, 15],
       [25, 30, 35],
       [45, 50, 55]])

In [48]:
arr_2d[0][0] #to access element matrix

np.int64(5)

In [49]:
arr_2d[0,1] #to access element matrix

np.int64(10)

In [68]:
arr_2d[1:,1:2]

array([[30],
       [50]])

# conditional selection

In [70]:
arr = np.arange(0,11)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
bool_arr = arr>5

In [75]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [76]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [80]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])